language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip

install:
  - go get -u golang.org/x/lint/golint/...
  - go get -u github.com/stretchr/testify/...
  - go get -u golang.org/x/net/context
script:
  - make test lint
  - go build ./...
